### ISSUE TITLE
How to download and install 

### ISSUE THREAD

**Issue by crushers** [Piker-Alpha/macosxbootloader#1]
Hello Piker-Alpha
I have a two question for you:
1.How to download macosxbootloader
2.How to install same boot loader?
Thanks in advanced!!!!!

**Comment by RickZaki** [comment]
Is this sufficient enough to close this issue?

https://github.com/Piker-Alpha/macosxbootloader/wiki/Compiling-Instructions

**Comment by Piker-Alpha** [comment]
Thanks RickZaki!
