### ISSUE TITLE
bug in _aullshr

### ISSUE THREAD

**Issue by tiamo010** [Piker-Alpha/macosxbootloader#19]
the function "_aullshr" is totally wrong in src/boot/x86/CompilerX86.cpp

correct implement is

```
extern "C" int __declspec(naked) _aullshr()
{
    __asm
    {
        cmp         cl, 64
        jae         RETZERO

        cmp         cl, 32
        jae         MORE32
        shrd        eax, edx, cl
        shr         edx, cl
        ret

    MORE32:
        mov         eax, edx
        xor         edx, edx
        and         cl, 31
        shr         eax, cl
        ret

    RETZERO:
        xor         eax, eax
        xor         edx, edx
        ret
    }
}
```

**Comment by Piker-Alpha** [comment]
Good catch. I personally never touched the file, but anyway. Thanks!

I also think that we need a link to a source file – from Microsoft – as a reference:

http://research.microsoft.com/en-us/um/redmond/projects/invisible/src/crt/md/i386/_ullshr.c.htm

**Edit**: Changes committed. Thanks again!
